class CreateHundredColumns < ActiveRecord::Migration[6.0]
  def change
    create_table :hundred_columns do |t|
      t.string :item1
      t.string :item2
      t.string :item3
      t.string :item4
      t.string :item5
      t.string :item6
      t.string :item7
      t.string :item8
      t.string :item9
      t.string :item10
      t.string :item11
      t.string :item12
      t.string :item13
      t.string :item14
      t.string :item15
      t.string :item16
      t.string :item17
      t.string :item18
      t.string :item19
      t.string :item20
      t.string :item21
      t.string :item22
      t.string :item23
      t.string :item24
      t.string :item25
      t.string :item26
      t.string :item27
      t.string :item28
      t.string :item29
      t.string :item30
      t.string :item31
      t.string :item32
      t.string :item33
      t.string :item34
      t.string :item35
      t.string :item36
      t.string :item37
      t.string :item38
      t.string :item39
      t.string :item40
      t.string :item41
      t.string :item42
      t.string :item43
      t.string :item44
      t.string :item45
      t.string :item46
      t.string :item47
      t.string :item48
      t.string :item49
      t.string :item50
      t.string :item51
      t.string :item52
      t.string :item53
      t.string :item54
      t.string :item55
      t.string :item56
      t.string :item57
      t.string :item58
      t.string :item59
      t.string :item60
      t.string :item61
      t.string :item62
      t.string :item63
      t.string :item64
      t.string :item65
      t.string :item66
      t.string :item67
      t.string :item68
      t.string :item69
      t.string :item70
      t.string :item71
      t.string :item72
      t.string :item73
      t.string :item74
      t.string :item75
      t.string :item76
      t.string :item77
      t.string :item78
      t.string :item79
      t.string :item80
      t.string :item81
      t.string :item82
      t.string :item83
      t.string :item84
      t.string :item85
      t.string :item86
      t.string :item87
      t.string :item88
      t.string :item89
      t.text :item90
      t.text :item91
      t.text :item92
      t.text :item93
      t.text :item94
      t.text :item95
      t.text :item96
      t.text :item97
      t.text :item98
      t.text :item99
      t.text :item100

      t.timestamps
    end
  end
end
